= Hardware specifications

Where did your run your tests? A laptop, or goldengate?
  
  I ran the test on a Ubuntu virtual machine installed on my laptop.

What are the performance specifications of the machine: number and speed of
processors, size of RAM? (use `lscpu` and `free -m`)

  Number of processors in VM: 2
  Processor: Apple M1 Pro (2 efficiency cores + 8 performance cores)
  Speed of processors: It is not displayed on lscpu, but I know my laptop's cpu clock speed is either 2.0GHz (efficiency core) or 3.2GHz (performance core). 
  VM RAM size: 3911MB

= Single-process mandelbrot

Run your executable, `single_mandelbrot`, with the following sizes and record
the amount of time it takes to compute each image.

[cols="1,1"]
!===
| Size | Time (s) 
| 100 | 0.053753
| 400 | 0.371078
| 800 | 1.384089
| 1000 | 2.144881
| 2000 | 8.442486
!===

= Multi-process mandelbrot

Run your executable, `multi_mandelbrot`, with the following sizes and record
the amount of time it takes to compute each image.

[cols="1,1"]
!===
| Size | Time (s) 
| 100 | 0.033863
| 400 | 0.211574
| 800 | 0.722606
| 1000 | 1.106408
| 2000 | 4.295165
!===
