/*----------------------------------------------
 * Author: Louis jiang 
 * Date: Feb 22, 2023
 * Description
 * A program that provides a function to write .ppm binary image files
 ---------------------------------------------*/
#include "write_ppm.h"
#include <stdio.h>
#include <string.h>

// implement *one* (but do not remove the other one)!

void write_ppm(const char* filename, struct ppm_pixel* pixels, int w, int h) {
  FILE* fp = fopen(filename, "wb");
  fprintf(fp, "P6\n# Generated by \"write_ppm\" function.");
  fprintf(fp, "\n%i %i\n%i\n", h, w, 255);
  fwrite(pixels, sizeof(struct ppm_pixel), h * w, fp);
  fclose(fp);
}

void write_ppm_2d(const char* filename, struct ppm_pixel** pixels, int w, int h) {

}

